baseURL: "http://localhost:1313/"
languageCode: en-us
title: Title
theme: hugo-tailwind
paginate: "10"
summaryLength: "10"
outputs:
  home:
    - HTML
    - RSS
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  plugins:
    js:
      - link: plugins/jquery/jquery.min.js
        attributes: ""
      - link: plugins/lunr/lunr.min.js
        attributes: ""
